## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [5]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [10]:
print(app_train.shape)

(307511, 122)

#### 列出所有欄位

In [33]:
print(app_train.columns)

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [40]:
app_train.iloc[5:10, :]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
5,100008,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,454500.0,"Spouse, partner",State servant,Secondary / secondary special,Married,House / apartment,0.035792,-16941,-1588,-4970.0,-477,NaN,1,1,1,1,1,0,Laborers,2.0,2,2,WEDNESDAY,16,0,0,0,0,0,0,Other,NaN,0.354225,0.621226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2536.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.0,1560726.0,41301.0,1395000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.035792,-13778,-3130,-1213.0,-619,17.0,1,1,0,1,1,0,Accountants,3.0,2,2,SUNDAY,16,0,0,0,0,0,0,Business Entity Type 3,0.774761,0.724000,0.492060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-1562.0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,1530000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.003122,-18850,-449,-4597.0,-2379,8.0,1,1,1,1,0,0,Managers,2.0,3,3,MONDAY,16,0,0,0,0,1,1,Other,NaN,0.714279,0.540654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-1070.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.0,405000.0,20250.0,405000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.019689,-14469,-2019,-14437.0,-3992,NaN,1,1,0,1,0,0,Laborers,1.0,2,2,THURSDAY,8,0,0,0,0,0,0,Electricity,NaN,0.746644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-1673.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [44]:
app_train[['NAME_CONTRACT_TYPE', 'AMT_INCOME_TOTAL']]

       NAME_CONTRACT_TYPE  AMT_INCOME_TOTAL
0              Cash loans        202500.000
1              Cash loans        270000.000
2         Revolving loans         67500.000
3              Cash loans        135000.000
4              Cash loans        121500.000
5              Cash loans         99000.000
6              Cash loans        171000.000
7              Cash loans        360000.000
8              Cash loans        112500.000
9         Revolving loans        135000.000
10             Cash loans        112500.000
11             Cash loans         38419.155
12             Cash loans         67500.000
13             Cash loans        225000.000
14             Cash loans        189000.000
15             Cash loans        157500.000
16             Cash loans        108000.000
17        Revolving loans         81000.000
18        Revolving loans        112500.000
19             Cash loans         90000.000
20        Revolving loans        135000.000
21             Cash loans        202500.000
22             Cash loans        450000.000
23             Cash loans         83250.000
24             Cash loans        135000.000
25             Cash loans         90000.000
26             Cash loans        112500.000
27             Cash loans        112500.000
28             Cash loans        270000.000
29        Revolving loans         90000.000
30             Cash loans        292500.000
31             Cash loans        112500.000
32             Cash loans         90000.000
33             Cash loans        360000.000
34             Cash loans        135000.000
35             Cash loans        112500.000
36             Cash loans        198000.000
37             Cash loans        121500.000
38             Cash loans         99000.000
39        Revolving loans        180000.000
40             Cash loans        202500.000
41             Cash loans        202500.000
42             Cash loans        135000.000
43             Cash loans        108000.000
44             Cash loans        202500.000
45        Revolving loans         90000.000
46             Cash loans        202500.000
47             Cash loans         99000.000
48             Cash loans        130500.000
49             Cash loans        360000.000
50        Revolving loans         54000.000
51             Cash loans        540000.000
52             Cash loans         76500.000
53             Cash loans        225000.000
54             Cash loans         81000.000
55             Cash loans        180000.000
56             Cash loans         67500.000
57        Revolving loans         81000.000
58             Cash loans        360000.000
59             Cash loans        540000.000
60             Cash loans        180000.000
61             Cash loans        180000.000
62             Cash loans        324000.000
63             Cash loans        112500.000
64             Cash loans        180000.000
65             Cash loans        180000.000
66             Cash loans        180000.000
67        Revolving loans        225000.000
68        Revolving loans        157500.000
69             Cash loans        180000.000
70             Cash loans        180000.000
71             Cash loans        103500.000
72             Cash loans        225000.000
73             Cash loans        157500.000
74             Cash loans        135000.000
...                   ...               ...
307436         Cash loans        135000.000
307437         Cash loans         81000.000
307438         Cash loans        171000.000
307439         Cash loans        247500.000
307440         Cash loans        440100.000
307441         Cash loans        126000.000
307442         Cash loans        135000.000
307443         Cash loans         76500.000
307444    Revolving loans         90000.000
307445         Cash loans        180000.000
307446         Cash loans        270000.000
307447         Cash loans        135000.000
307448         Cash loans        207000.000
307449         Cash loans        315000.000
307450         Cash loans         54000.000
307451         Cash loans        450000.000
307452         Cash loans        153000.000
307453         Cash loans        135000.000
307454         Cash loans        157500.000
307455         Cash loans        157500.000
307456         Cash loans         94500.000
307457    Revolving loans        202500.000
307458         Cash loans        112500.000
307459         Cash loans        225000.000
307460         Cash loans        382500.000
307461         Cash loans        157500.000
307462         Cash loans        135000.000
307463         Cash loans        180000.000
307464         Cash loans         58500.000
307465         Cash loans        180000.000
307466         Cash loans        157500.000
307467    Revolving loans        247500.000
307468         Cash loans        135000.000
307469         Cash loans        202500.000
307470         Cash loans         90000.000
307471         Cash loans        112500.000
307472         Cash loans        135000.000
307473         Cash loans         90000.000
307474         Cash loans        135000.000
307475         Cash loans        144000.000
307476         Cash loans        135000.000
307477         Cash loans        360000.000
307478         Cash loans        225000.000
307479         Cash loans        112500.000
307480         Cash loans         81000.000
307481         Cash loans        225000.000
307482         Cash loans        225000.000
307483         Cash loans         99000.000
307484         Cash loans        540000.000
307485    Revolving loans        270000.000
307486         Cash loans        292500.000
307487         Cash loans        117000.000
307488         Cash loans        157500.000
307489         Cash loans        225000.000
307490         Cash loans         81000.000
307491         Cash loans         90000.000
307492         Cash loans        585000.000
307493         Cash loans        135000.000
307494         Cash loans        270000.000
307495         Cash loans        180000.000
307496    Revolving loans        360000.000
307497         Cash loans        180000.000
307498         Cash loans        198000.000
307499         Cash loans         81000.000
307500         Cash loans        261000.000
307501         Cash loans         81000.000
307502         Cash loans         94500.000
307503         Cash loans        112500.000
307504         Cash loans        153000.000
307505         Cash loans        112500.000
307506         Cash loans        157500.000
307507         Cash loans         72000.000
307508         Cash loans        153000.000
307509         Cash loans        171000.000
307510         Cash loans        157500.000

[307511 rows x 2 columns]